version: '3'
services:
  db:
    image: postgres:12-alpine
    # ports:
    #   - 0:5432
    env_file:
      .env.docker
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    container_name: himama
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/himama
    ports:
      - "3000:3000"
        # command: rails s -b 0.0.0.0 #thin -a 0.0.0.0 -p 3000 start
    env_file:
      .env.docker
    depends_on:
      - db

